name: Build and sign image
on:
  push:
    branches:
      - main

jobs:
  selftest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: file.txt
